---
- hosts: localhost
  tasks:
  - name: check if htpasswd file exists
    stat:
      path: /tmp/passwordFile
    register: passFile
  - name: generate htpasswd to login to openshift
    shell: |
      htpasswd -b -c /tmp/passwordFile {{ oc_username }} {{ oc_password }}
    when:
      - passFile.stat.exists == false