---
- hosts: all
  tasks:
  - name: check if ansible-config folder exists
    stat:
      path: /opt/ansible-config
    register: check_ansible_config
  - name: ansible create ansible-config directory
    file:
     path: /opt/ansible-config
     state: directory
    when: not check_ansible_config.stat.exists
  - name: Create  repo location
    git:
      repo: "https://{{ githubuser | urlencode }}:{{ gitlabpassword }}@gitlab.consulting.redhat.com/rto/ansible-tower-configs.git"
      dest: /opt/ansible-config
      version: "{{ branch }}"
  - name: ansible create ansible-config directory
    file:
     path: /opt/ansible-config
     state: directory
  - name: Updating Ansible Tower Configuration
    shell:  |
      #!/bin/bash
      rm /var/log/tower-config.log
      tower-cli config verify_ssl false | tee /var/log/tower-config.log
      tower-cli login admin -p {{ tower_password }} | tee /var/log/tower-config.log
      tower-cli send /opt/ansible-config/towerconfigs/{{ ansible_tower_config }} | tee /var/log/tower-config.log
    when: skip_tower_config
  - name: Updating OpenShift Inventory
    shell:  |
      tower-cli config verify_ssl false | tee /var/log/openshift-inventory-push.log
      tower-cli login admin -p {{ tower_password }} | tee /var/log/openshift-inventory-push.log
      tower-manage inventory_import --source=/opt/ansible-config/environments/{{ awxinventorypath }} --inventory-name={{ awxinventoryname }} --overwrite --overwrite-vars | tee /var/log/openshift-inventory-push.log