---
- hosts: all
  tasks:
  - name: check if htpasswd file exists
    stat:
      path: /home/tosin/openshift-ansible/passwordFile
    register: passFile
  - name: generate password for openshift htpasswd
    copy:
      dest: "/tmp/temppassword"
      content: |
        {{ oc_password }}
    when:
      - passFile.stat.exists == false
  - name: generate htpasswd to login to openshift
    shell: |
      htpasswd -b -c  /tmp/temppassword {{ oc_username }}
    when:
      - passFile.stat.exists == false