---
- hosts: master
  tasks:
  - name: check if htpasswd file exists
    stat:
      path: /home/tosin/openshift-ansible/passwordFile
    register: passFile
  - name: generate password for openshift htpasswd
    lineinfile:
      path: /tmp/temppassword
      line: '{{ oc_password }}'
    when:
      - passFile.stat.exists == false
  - name: generate htpasswd to login to openshift
    shell: |
      htpasswd -b -c ~/temp/password {{ oc_username }}
    when:
      - passFile.stat.exists == false