---
- hosts: all
  tasks:
  - name: check if htpasswd file exists
    stat:
      path: /home/tosin/openshift-ansible/passwordFile
    register: passFile
  - name: generate htpasswd to login to openshift
    shell: |
      htpasswd -b -c   /home/tosin/openshift-ansible/passwordFile {{ oc_username }} {{ oc_password }}
    when:
      - passFile.stat.exists == false