- hosts: all
  tasks:
  - name: update named.conf with new zone {{ zone_name }}
    blockinfile:
      path: /etc/named.conf
      block: |
        zone "{{ zone_name }}" IN {
          type master;
          file "{{ key_name }}";
          notify yes;
          allow-update { none; };
        };
  - name: running configure dns keys on server
    script: configure_dns_keys.sh "{{ key_name }}"   "{{ server_ip }}" "{{ zone_name }}" | tee /var/log/configure_dns_keys.log