- hosts: all
  tasks:
  - name: Check if port {{ port_num }} is listening
    wait_for:
      port: "{{ port_num }}"
      delay: 5
      timeout: "{{ default_timeout }}"
      msg: "Timeout waiting for {{ port_num }}  to respond"
    ignore_errors: no