---
- hosts: all
  gather_facts: false
  tasks:
  - name: Ansible check if {{ user_data_file }} exists.
    stat:
      path: "{{ user_data_file }}"
    register: file_details
  - debug:
      msg: "The {{ user_data_file }} exists"
    when: file_details.stat.exists
  - name: Retreving DNS Key
    shell: |
      cat "{{ user_data_file }}"  | grep secret  | awk '{print $2}' | sed 's/"//g' | sed 's/;//g'
    register: user_data_action
    when: file_details.stat.exists
  - name: Debug
    debug: msg="the value of {{ user_data_file }} is {{ user_data_action.stdout }}"
    when: file_details.stat.exists
  - name: Set Apache URL
    set_fact:
      vault_dns_key: "{{ user_data_action.stdout }}"
    when: file_details.stat.exists
  - include_vars: dns_key/dns_key
  - name: Add or modify {{ a_record }} A to {{ ip_address }}"
    nsupdate:
      key_name: "{{ dns_key_name }}"
      key_secret: "{{ vault_dns_key }}"
      server: "0.0.0.0"
      zone: "{{ dns_zone }}"
      record: "{{ a_record }}"
      value: "{{ ip_address }}"