---
- name: Remove virtual machine
  hosts: all
  gather_facts: no
  
  tasks: 
  - name: Removing {{ vm_name }} virtual machine
    vmware_guest:
      hostname: "{{ vcenter_datacenter }}"
      validate_certs: no
      cluster: "{{ vcenter_ cluster }}"
      name: "{{ vm_name }}"
      state: absent