---
- hosts: all
  tasks:
  - name: "Test node name"
    debug:
      msg: "Conditional result: {{ item }}  inventory name {{inventory_hostname}}"
    when:  inventory_hostname  is search("{{ item }}")
    with_items:
      "{{ node_names }}"
  - name: Change the hostname to our standard
    hostname:
      name="{{ item }}.{{ fqdn }}"
    when:  inventory_hostname  is search("{{ item }}")
    with_items:
      "{{ node_names }}"
  - name: Fix /etc/hosts removing the old hostname
    tags:
      - hosts
    lineinfile:
      state=present
      dest=/etc/hosts
      line="{{ ansible_default_ipv4.address }} {{ vm_host_name }} {{ vm_host_name }}.{{ fqdn }}"
      regexp="^{{ ansible_default_ipv4.address }}"
    when:
      ansible_fqdn != "{{ vm_host_name }}.{{ fqdn }}"
  - name: Validate ansible_fqdn == inventory_hostname
    tags:
      - validate
    assert:
      that:
        ansible_fqdn == "{{ vm_host_name }}.{{ fqdn }}"
