---
- hosts: all
  tasks:
  - name: "Test node name"
    debug:
      msg: "Conditional result: {{ item }}  inventory name {{ inventory_hostname }}"
    when:  inventory_hostname  is search("{{ item }}")
    with_items:
      "{{ node_names }}"
  - name: Change the hostname to our standard
    hostname:
      name="{{ item }}.{{ fqdn }}"
    when:  inventory_hostname  is search("{{ item }}")
    with_items:
      "{{ node_names }}"
  - name: Fix /etc/hosts removing the old hostname
    tags:
      - hosts
    lineinfile:
      state=present
      dest=/etc/hosts
      line="127.0.1.1 {{ item }} {{ item }}.{{ fqdn }}"
      regexp="^{{ ansible_default_ipv4.address }}"
    when:  inventory_hostname  is search("{{ item }}")
    with_items:
      "{{ node_names }}"
  - name: restart machine
    command: shutdown -r now "Ansible updates triggered"
    async: 0
    poll: 0
    ignore_errors: True
    when:
      reboot is defined
  - name: Waiting for server to come back up
    local_action: wait_for host="{{ inventory_hostname }}" port=22 state=started
  - name: Validate ansible_fqdn ==  "{{ item }}.{{ fqdn }}"
    tags:
      - validate
    assert:
      that:
        ansible_fqdn == "{{ item }}.{{ fqdn }}"
    when:  inventory_hostname  is search("{{ item }}")
    with_items:
      "{{ node_names }}"
