---
- hosts: all
  tasks:
  - name: Change the hostname to our standard
  hostname:
    name="{{ vm_host_name }}.{{ fqdn }}"
  when:
    ansible_fqdn != "{{ vm_host_name }}.{{ fqdn }}"
  - name: Fix /etc/hosts removing the old hostname
    tags:
      - hosts
    lineinfile:
      state=present
      dest=/etc/hosts
      line="{{ ansible_default_ipv4.address }} {{ vm_host_name }} {{ vm_host_name }}.{{ fqdn }}"
      regexp="^{{ ansible_default_ipv4.address }}"
    when:
      ansible_fqdn != "{{ vm_host_name }}.{{ fqdn }}"
  - name: Validate ansible_fqdn == inventory_hostname
    tags:
      - validate
    assert:
      that:
        ansible_fqdn == "{{ vm_host_name }}.{{ fqdn }}"
