---
- hosts: all
  tasks:
  - name: "Test node name"
    debug:
      msg: "Conditional result: {{ item }}  inventory name {{ inventory_hostname }}"
    when:  inventory_hostname  is search("{{ item }}")
    with_items:
      "{{ node_names }}"
  - name: Change the hostname to our standard
    hostname:
      name="{{ item }}.{{ fqdn }}"
    when:  inventory_hostname  is search("{{ item }}")
    with_items:
      "{{ node_names }}"
  - name: Fix /etc/hosts removing the old hostname
    tags:
      - hosts
    lineinfile:
      state=present
      dest=/etc/hosts
      line="127.0.1.1 {{ item }} {{ item }}.{{ fqdn }}"
      regexp="^{{ ansible_default_ipv4.address }}"
    when:  inventory_hostname  is search("{{ item }}")
    with_items:
      "{{ node_names }}"
  - name: reboot {{ inventory_hostname }}"
    shell: sleep 2 && shutdown -r now "Ansible package updates triggered"
    async: 1
    poll: 0
    ignore_errors: true
    become: true
  - name: Wait 60 seconds, but only start checking after 30 seconds
    wait_for_connection:
      delay: 30
      timeout: 60
  - name: Validate ansible_fqdn ==  "{{ item }}.{{ fqdn }}"
    tags:
      - validate
    assert:
      that:
        ansible_fqdn == "{{ item }}.{{ fqdn }}"
    when:  inventory_hostname  is search("{{ item }}")
    with_items:
      "{{ node_names }}"
