---
- hosts: all
  tasks:
  - name: Add EPEL repository for CentOS deployments
    yum_repository:
      name: epel
      description: EPEL YUM repo
      baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
    when:
      - ansible_distribution == "CentOS"
  - name: Importing rpm gpg-key for CentOS deployments.
    shell: |
       rpm --import http://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-7 >> /tmp/epelgpgimport.log
    when:
      - ansible_distribution == "CentOS"
  - name: Register as auto-subscribe to red hat subscription.
    redhat_subscription:
      state: present
      username: "{{ rhel_username }}"
      password: "{{ rhel_password }}"
      auto_attach: true
    when:
      - ansible_distribution == "RedHat"
  - name: Enable a Ansible 2.6 repository
    rhsm_repository:
      name: rhel-7-server-ansible-2.6-rpms
      state: enabled
    when:
      - ansible_distribution == "RedHat"
  - name: Enable rhel-7-server-rpms repository
    rhsm_repository:
      name: rhel-7-server-rpms
    when:
      - ansible_distribution == "RedHat"
  - name: Enable rhel-7-server-extras-rpms repository
    rhsm_repository:
      name: rhel-7-server-extras-rpms
      state: enabled
    when:
      - ansible_distribution == "RedHat"
  - name: Enable rhel-7-server-optional-rpms repository
    rhsm_repository:
      name: rhel-7-server-optional-rpms
      state: enabled
    when:
      - ansible_distribution == "RedHat"
  - name: Add Docker repo
    get_url:
      url: https://download.docker.com/linux/centos/docker-ce.repo
      dest: /etc/yum.repos.d/docker-ce.repo
    when:
      - ansible_distribution == "CentOS"
  - name: upgrade all packages
    yum:
      name: '*'
      state: latest
  - name: install base packages
    yum:
      name:
      - wget
      - git
      - net-tools
      - bind-utils
      - yum-utils
      - iptables-services
      - bridge-utils
      - bash-completion
      - kexec-tools
      - sos
      - psacct
      - vim
      state: present
  - name: install required packages for CENTOS
    yum:
      name:
        - pyOpenSSL
        - device-mapper-event-libs
        - device-mapper-libs
        - httpd-tools
        - java-1.8.0-openjdk-devel.x86_64
        - tmux
        - patch
        - lvm2
        - docker-ce
        - python-pip
      state: present
    when:
      - ansible_distribution == "CentOS"
  - name: Run script to modifiy terminal layout
    shell: |
         pip install passlib
    when:
      - ansible_distribution == "CentOS"
  - name: Download ansible-2.6.5 rpm for centos
    get_url:
      url: https://releases.ansible.com/ansible/rpm/release/epel-7-x86_64/ansible-2.6.5-1.el7.ans.noarch.rpm
      dest: /tmp/ansible-2.6.5-1.el7.ans.noarch.rpm
    when:
      - ansible_distribution == "CentOS"
  - name: Installing ansible-2.6.5-1.el7.ans.noarch.rpm on CentOS.
    shell: |
      yum install /tmp/ansible-2.6.5-1.el7.ans.noarch.rpm -y >> /tmp/ansibleinstall.log
    when:
      - ansible_distribution == "CentOS"
  - name: Install a list of packages
    yum:
      name:
        - ansible
        - docker
        - httpd-tools
        - java-1.8.0-openjdk-devel.x86_64
        - tmux
      state: present
    when:
      - ansible_distribution == "RedHat"
  - name: Cloning OpenShift release-3.11 to machine
    git:
      repo: 'https://github.com/openshift/openshift-ansible.git'
      dest: /home/{{ rhel_user }}/openshift-ansible
      version: release-3.11
  - name: change openshift-ansible owner to {{ rhel_user }}
    file:
      path: /home/{{ rhel_user }}/openshift-ansible
      owner: "{{ rhel_user }}"
      group: "{{ rhel_user }}"
      mode: 0775
  - name: Cloning  Bash full of Colors to machine
    git:
      repo: 'https://github.com/tosin2013/bash-full-of-colors.git'
      dest: /home/{{ rhel_user }}/bash-full-of-colors
  - name: Run script to modifiy terminal layout
    shell: |
      cd /home/{{ rhel_user }}
      [ -f .bashrc ] && mv -v .bashrc /tmp/bashrc.old
      [ -f .bash_profile ] && mv -v .bash_profile /tmp/bash_profile.old
      [ -f .bash_aliases ] && mv -v .bash_aliases /tmp/bash_aliases.old
      [ -f .bash_logout ] && mv -v .bash_logout /tmp/bash_logout.old
      cp /home/{{ rhel_user }}/bash-full-of-colors/bashrc.sh /home/{{ rhel_user }}/.bashrc
      cp /home/{{ rhel_user }}/bash-full-of-colors/bash_profile.sh /home/{{ rhel_user }}/.bash_profile
      cp /home/{{ rhel_user }}/bash-full-of-colors/bash_aliases.sh /home/{{ rhel_user }}/.bash_aliases
      cp /home/{{ rhel_user }}/bash-full-of-colors/bash_logout.sh /home/{{ rhel_user }}/.bash_logout
      rm -rf bash-full-of-colors/